# -*- coding: utf-8 -*-
"""k_nearestneighbors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qfPB4NV6CgaaGvEF9034iTuCM9UOs7N
"""

from sklearn.datasets import load_digits
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

digits = load_digits()
X, y = digits.data, digits.target

X_train, X_test, y_train, y_test = train_test_split(X, y)

model = KNeighborsClassifier()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))