# -*- coding: utf-8 -*-
"""support_vector_machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJUC3DKkFZLY3B7WBgh34o9MRm9E5QNj
"""

from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(X, y)

model = SVC()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))